---
output: html_document
---

## <font color='#0065bd'>Research Interests</font>

I work mainly in the field of functional data analysis (FDA), which is a sub-field of mathematical statistics, centered around the problem of statistical inference on the law of a continuous-time random process given multiple realizations of such a process. I am particularly interested in functional data on multi-dimensional domains, where the random process is not only a function of time but also e.g. of space.
My research focuses on methodological aspects, but computational costs and numerical aspects naturally enter into consideration due to the size and continuity of multi-dimensional functional data.
In another line of research, I develop optimization algorithms for NP-hard versions of principal component analysis (PCA) such as matrix completion, robust PCA or sparse PCA.
The intersection between my two main lines of research is the concept of low-rankness (in different forms), which I consider to be powerful and useful in many applied problems.

## <font color='#0065bd'>Work in Progress</font>

* K. Waghmare, T. Masak & V. Panaretos: Functional Graphical LASSO
* C. Kuemmerle, T. Masak & F. Krahmer: Optimal Quadratic Models for Low-rank Optimization

## <font color='#0065bd'>Publications</font>

* T. Masak & V. Panaretos (2022) Random Surface Covariance Estimation by Shifted Partial Tracing. *Journal of the American Statistical Association*.
    - [open access](https://www.tandfonline.com/doi/full/10.1080/01621459.2022.2061982)
* T. Masak, S. Sarkar & V. Panaretos (2023) Separable Expansions for Covariance Estimation via the Partial Inner Product. *Biometrika*.
    - [open access](https://academic.oup.com/biomet/article/110/1/225/6609757)
    - [arXiv version](https://arxiv.org/abs/2007.12175) can be of interest in this case
* T. Masak, T. Rubín & V. Panaretos (2022) Sprsely Observed Random Surfaces. *Journal of Computational and Graphical Statistics*.
    - [open access](https://www.tandfonline.com/doi/full/10.1080/10618600.2022.2034640)
* T. Masak (2017) Iteratively Reweighted Least Squares Algorithm for Sparse Principal Component Anlysis with Application to Voting Records. *Statistika: Statistics and Economy Journal*.
    - [open access](https://www.czso.cz/documents/10180/45606531/32019717q3088.pdf/24cc2082-712b-4386-a5b5-dfcd56f3ff29?version=1.0)

## <font color='#0065bd'>Software</font>

`surfcov` package

* [publicly avilable](https://github.com/TMasak/surfcov)
* covariance estimation for random surfaces beyond separability
* implements methodologies from Masak & Panaretos (2022) and Masak, Sarkar & Panaretos (2023)

`cerss` package

* [publicly available](https://github.com/TMasak/cerss)
* allows reproduction of the simulation studies and real data applications in Masak & Panaretos (2022) and Masak, Sarkar & Panaretos (2023) and Masak, Rubín & Panaretos (2022)

`fglasso` package
 
* code to the functional graphical lasso paper above
* not yet public, available upon request



