---
output: html_document
---

## <font color='#0065bd'>Lectures</font>

Statistical Computation and Visualization

* core course for Masters in Statistics at EPFL
    - full semester course, designated for the 1st semester of the MSc program
* the [coursebook entry](https://edu.epfl.ch/coursebook/fr/statistical-computation-and-visualisation-MATH-517) is slightly outdated, I have developed a new course from scratch
* all the materials are publicly available in [this repo](https://github.com/TMasak/StatComp)

Applied Statistics

* core course for Masters in Statistics at EPFL
    - full semester course, designated for the 2nd semester of the MSc program
* the [coursebook entry](https://edu.epfl.ch/coursebook/en/applied-statistics-MATH-516) is slightly outdated, I am developing a new course from scratch
* all the materials are publicly available in [this repo](https://github.com/TMasak/AppStat)

## <font color='#0065bd'>Mentoring</font>

Below is a list of projects I have supervised at EPFL. A semester project (either Bachelor or Master) is worth 10 credits, while the Master project is worth 30 credits.

* Covariance Estimation for Matrix-variate Data, Master semester project, 2023
* Classification of Brain Voxels from Dynamic Contrast-Enhanced MRI, Master's thesis, 2022
* Clustering Functional Data to Localize Damaged Tissue in MRI, Master semester project, 2022
* Forecasting Functional Time Series, Master semester project, 2021, jointly with Prof. V. Panaretos & L. Santoro
* Functional Principal Component Analysis with Application to COVID-19 Dynamics, Bachelor semester project, 2021, jointly with Prof. V. Panaretos & L. Santoro
* Introduction to Non-parametric Density Estimation, Bachelor semester project, 2020, informally with Prof. V. Panaretos
* Modelling of Selective Nerve Stimulation for Prostheses with Sensory Feedback Using Machine Learning Methods, Master semester project, 2019, with Prof. F. Eisenbrandt & Dr. I. Malinovic
* Matrix-variate Normal Distribution, Bachelor semester project, 2019, with Prof. V. Panaretos

## <font color='#0065bd'>Exercises</font>

Here is a list of semester-long courses that I have taught or TAed in the past. Being a teaching assistant (TA) at EPFL means answering questions of the students during the exercise classes and grading the homeworks and exams. I was always a "principal TA", which in addition comprises administrating the course webpage (or the Moodle page and forums) and preparation of the exams. At the other universities, my work additionally consisted of independent in-classroom teaching of the regular exercise classes. I consider myself adept in teaching various regression methods and time series analysis, as well as introductory probability and statistical inference classes for both bachelor and master students of various backgrounds, inclcuding mathematicians, computer scientists, economists and engineers.

* Linear Models, EPFL (2022,2021,2020,219)
* Statistique pour Mathematiciens, EPFL (2020)
* Time Series, EPFL (2019,2018)
* Statistics for Data Science, EPFL (2018)
* Time Series Analysis, Technical University of Munich (TUM, 2017)
* Probability and Mathematical Statistics, Charles University (2015)
* Statistics, Institute of Economic Studies (2015)
* Mathematics 1A, Czech Technical University (2015)



